- name: Install htop
  hosts: all
  become: yes

  tasks:
    # - name: install epel-release
    #   ansible.builtin.dnf:
    #     name: epel-release
    #     state: present
    
    # - name: install htop
    #   ansible.builtin.dnf:
    #     name: htop
    #     state: present

    - name: Uninstall htop
      ansible.builtin.dnf:
        name: htop
        state: absent
