- name: Install nginx
  hosts: all
  become: yes

  vars_files: 
    vars.yml

  tasks:
    # - name: Install nginx package
    #   ansible.builtin.dnf:
    #     name: "{{ package_name }}"
    #     state: present


    # - name: Uninstall nginx
    #   ansible.builtin.dnf:
    #     name: "{{ package-name }}-{{ version }}"
    #     state: absent
    - name: Checking service is running
      ansible.builtin.service:
        name: "{{service_name}}"
        state: started
        enabled: yes