- name: Create user and group
  hosts: all
  become: yes

  vars_files:
   vars.yml

  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present

    - name: Create user for group 
      ansible.builtin.user:
        name: "{{user_name}}"
        state: present
        group: "{{group_name}}"
        create_home: yes